version: '3'

services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: joboard
      MYSQL_ROOT_PASSWORD: 
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
